### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by snevolin** [vovochka404/deadbeef-statusnotifier-plugin#1]
Пытаюсь сборать с cmake на Fedora 22 x86_64, выдаёт ошибки:
-- checking for module 'dbusmenu-glib-0.4'
--   package 'dbusmenu-glib-0.4' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:40 (PKG_CHECK_MODULES)

В репозитории такого найти не могу :(

**Comment by vovochka404** [comment]
https://apps.fedoraproject.org/packages/libdbusmenu

С федорой никогда не работал, но пакеты есть.
Тебе нужны libdbusmenu-devel, libdbusmenu-gtk3-devel
Ну и если тебе нужна gtk2 версия, то libdbusmenu-gtk-devel
