### ISSUE TITLE
Can't compile, no deadbeef.h found

### ISSUE THREAD

**Issue by kotyz85** [vovochka404/deadbeef-statusnotifier-plugin#2]
I have this error:

CMake Error at CMakeLists.txt:46 (MESSAGE):
  Can't find folder containing deadbeef/deadbeef.h

-- Configuring incomplete, errors occurred!

on Kubuntu 15.10, deadbeef installed from this ppa: https://launchpad.net/~starws-box/+archive/ubuntu/deadbeef-player?field.series_filter=wily

**Comment by vovochka404** [comment]
deadbeef-plugins-dev - install this package (from that ppa). It contains deadbeef.h
