### ISSUE TITLE
Segfault in libdbusmenu-glib

### ISSUE THREAD

**Issue by vovochka404** [vovochka404/deadbeef-statusnotifier-plugin#4]
Segmentation Fault
backtrace() returned 13 addresses
/usr/bin/deadbeef() [0x403ff0]
/lib64/libc.so.6(+0x35200) [0x7fc585dfd200]
/usr/lib64/libdbusmenu-glib.so.4(dbusmenu_menuitem_get_id+0x13) [0x7fc57bb53083]
/usr/lib64/libdbusmenu-glib.so.4(+0xdb76) [0x7fc57bb58b76]
/usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x135) [0x7fc583c65b65]
/usr/lib64/libglib-2.0.so.0(+0x4bed8) [0x7fc583c65ed8]
/usr/lib64/libglib-2.0.so.0(g_main_loop_run+0x6a) [0x7fc583c6619a]
/usr/lib64/libgtk-3.so.0(gtk_main+0x85) [0x7fc5853f3f05]
/usr/lib64/deadbeef/ddb_gui_GTK3.so(gtkui_thread+0x778) [0x7fc585b4b9d8]
/usr/lib64/deadbeef/ddb_gui_GTK3.so(+0x31c55) [0x7fc585b4bc55]
/usr/bin/deadbeef() [0x403cfc]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fc585de9b05]
/usr/bin/deadbeef() [0x403efc]

**Comment by SkyMaverick** [comment]
Not reproduced in new releases. This problem has probably been resolved.
