### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by elektr0nik** [vovochka404/deadbeef-statusnotifier-plugin#5]
Hi! I can't compile plugin on Debian.
cmake deadbeef-plugins-dev libdbusmenu-glib-dev libgtk-3-dev installed.
Log of `make`:
[ 11%] Generating enums.h
/usr/bin/glib-mkenums: /home/user/deadbeef-statusnotifier-plugin-master/extras/statusnotifier/src/statusnotifier.h:118: Failed to parse `    /*< private >*/ '
[ 22%] Generating enums.c
/usr/bin/glib-mkenums: /home/user/deadbeef-statusnotifier-plugin-master/extras/statusnotifier/src/statusnotifier.h:118: Failed to parse `    /*< private >*/ '
Scanning dependencies of target sni_gtk3
[ 33%] Building C object CMakeFiles/sni_gtk3.dir/src/x11-force-focus.c.o
[ 44%] Building C object CMakeFiles/sni_gtk3.dir/src/menu.c.o
[ 55%] Building C object CMakeFiles/sni_gtk3.dir/src/sni.c.o
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c: In function ‘on_activate_requested’:
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:49:33: error: ‘DB_plugin_action_t {aka struct DB_plugin_action_s}’ has no member named ‘callback2’; did you mean ‘callback’?
         toggle_mainwindow_action->callback2 (toggle_mainwindow_action, -1);
                                 ^~
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c: In function ‘sni_update_tooltip’:
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:220:47: error: ‘ddb_gtkui_t {aka struct <anonymous>}’ has no member named ‘get_cover_art_pixbuf’
                 GdkPixbuf * buf = gtkui_plugin->get_cover_art_pixbuf  (deadbeef->pl_find_meta (track, ":URI"), artist, album, 128, NULL, NULL);
                                               ^~
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:224:39: error: ‘ddb_gtkui_t {aka struct <anonymous>}’ has no member named ‘cover_get_default_pixbuf’
                     buf = gtkui_plugin->cover_get_default_pixbuf ();
                                       ^~
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c: In function ‘deadbeef_preferences_activate’:
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:321:23: error: ‘DB_plugin_action_t {aka struct DB_plugin_action_s}’ has no member named ‘callback2’; did you mean ‘callback’?
     preferences_action->callback2 (preferences_action, 0);
                       ^~
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c: In function ‘sni_connect’:
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:366:62: error: ‘DDB_GTKUI_PLUGIN_ID’ undeclared (first use in this function)
     gtkui_plugin = (ddb_gtkui_t *)deadbeef->plug_get_for_id (DDB_GTKUI_PLUGIN_ID);
                                                              ^~~~~~~~~~~~~~~~~~~
/home/user/deadbeef-statusnotifier-plugin-master/src/sni.c:366:62: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/sni_gtk3.dir/build.make:118: recipe for target 'CMakeFiles/sni_gtk3.dir/src/sni.c.o' failed
make[2]: *** [CMakeFiles/sni_gtk3.dir/src/sni.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sni_gtk3.dir/all' failed
make[1]: *** [CMakeFiles/sni_gtk3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vovochka404** [comment]
Do you have /usr/include/deadbeef/gtkui_api.h file on your system? It must be provided by deadbeef-plugins-dev.
And what version of deadbeef are u useing?

**Comment by elektr0nik** [comment]
Do you have /usr/include/deadbeef/gtkui_api.h file on your system? Yes.
Deadbeef version - 0.7.2

**Comment by vovochka404** [comment]
And what version of deadbeef-plugins-dev  do u have?
Can you post content of /usr/include/deadbeef/gtkui_api.h somewhere? (pastebin.com for example)

**Comment by elektr0nik** [comment]
version of deadbeef-plugins-dev was wrong, i'm sory for my inattention

**Comment by vovochka404** [comment]
Now everything works?

**Comment by elektr0nik** [comment]
Yes, now all is ok. Thanks
